<a href="https://colab.research.google.com/github/CatalinaDeras24/etl-data-pipeline/blob/main/Notebook/Aseguradoras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url="https://raw.githubusercontent.com/CatalinaDeras24/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

In [4]:
df=pd.read_csv(url)

In [5]:
df.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

Exploracion de datos

In [7]:
df.shape

(15, 4)

In [8]:
df.columns

Index(['id_aseguradora', 'nombre', 'pais', 'rating_riesgo'], dtype='object')

In [9]:
df.isnull().sum()

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

LIMPIEZA DE DATOS

In [15]:
aseguradoras= df.copy()

In [20]:
aseguradoras['rating_riesgo']= aseguradoras['rating_riesgo'].replace('B', 'Bajo')

In [23]:
aseguradoras.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador          Bajo

In [22]:
aseguradoras['rating_riesgo']= aseguradoras['rating_riesgo'].replace('B', 'Bajo')
aseguradoras['rating_riesgo']= aseguradoras['rating_riesgo'].replace('M', 'Medio')
aseguradoras['rating_riesgo']= aseguradoras['rating_riesgo'].replace('A', 'Alto')