<a href="https://colab.research.google.com/github/CatalinaDeras24/etl-data-pipeline/blob/main/Notebook/polizas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url="https://raw.githubusercontent.com/CatalinaDeras24/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

Exploración de datos

In [ ]:
df.shape

(25150, 9)

In [ ]:
df.columns

Index(['id_poliza', 'fecha_emision', 'id_cliente', 'id_corredor',
       'id_aseguradora', 'id_tipo_seguro', 'prima', 'comision',
       'monto_asegurado'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

In [ ]:
df.isnull().sum()

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

Limpieza de datos

In [ ]:
polizas= df.copy()

In [ ]:
for col in polizas.select_dtypes(include='object').columns:
    polizas[col] = polizas[col].str.strip()

In [ ]:
cols = ['prima', 'comision', 'monto_asegurado']

def limpiar_numero(x):
    x = str(x).strip()

    if x in ['', '-', 'nan', 'None']:
        return pd.NA

    if ',' in x and '.' in x:
        if x.rfind(',') > x.rfind('.'):
            x = x.replace('.', '').replace(',', '.')
        else:
            x = x.replace(',', '')
    elif ',' in x:
        x = x.replace(',', '.')

    return pd.to_numeric(x, errors='coerce')

for col in cols:
    polizas[col] = polizas[col].apply(limpiar_numero)

In [ ]:
polizas['fecha_emision'] = pd.to_datetime(
    polizas['fecha_emision'],
    format='mixed',
    errors='coerce',
    dayfirst=True
)

In [ ]:
polizas['fecha_emision']=polizas['fecha_emision'].replace(['', 'nan', 'None', 'NULL'], pd.NA)

In [ ]:
polizas['fecha_emision'] = polizas['fecha_emision'].astype('string')
polizas['fecha_emision'] = polizas['fecha_emision'].replace('NaT', pd.NA)

In [ ]:
num_cols = ['prima', 'comision', 'monto_asegurado']

for col in num_cols:
    polizas[col] = pd.to_numeric(polizas[col], errors='coerce').astype(float)

polizas['fecha_emision'] = pd.to_datetime(polizas['fecha_emision'], errors='coerce').dt.date
polizas = polizas.where(pd.notna(polizas), None)

Separar datos válidos y rechazados

In [ ]:

validos = polizas.dropna(
    subset=['fecha_emision', 'prima', 'comision', 'monto_asegurado']
).copy()

rechazados = polizas[
    polizas[['fecha_emision', 'prima', 'comision', 'monto_asegurado']]
    .isna()
    .any(axis=1)
].copy()

Motivo de rechazo

In [ ]:
def motivo(row):
    motivos = []

    if pd.isna(row['fecha_emision']):
        motivos.append("Fecha de emisión inválida o vacía")

    if pd.isna(row['prima']):
        motivos.append("Prima inválida o vacía")

    if pd.isna(row['comision']):
        motivos.append("Comisión inválida o vacía")

    if pd.isna(row['monto_asegurado']):
        motivos.append("Monto asegurado inválido o vacío")

    return ", ".join(motivos)

Exportar archivos

In [ ]:

validos.to_csv("polizas_curated.csv", index=False)

rechazados.to_csv("polizas_rejects.csv", index=False)

Conectar con PostgreSQL Cloud

In [ ]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_a5iy_user:wejO7kM3iEylWf1mrkye7dj6P9rI4f6B@dpg-d6qu8ka4d50c73bk4lqg-a.oregon-postgres.render.com/etl_seguros_a5iy"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

Cargar datos en PostgreSQL

In [ ]:
validos.to_sql(
    'polizas_curated',
    engine,
    if_exists='append',
    index=False
)

632

In [ ]:

rechazados.to_sql(
    'polizas_rejects',
    engine,
    if_exists='append',
    index=False
)

518

Validar la carga

In [ ]:
pd.read_sql('SELECT * FROM "polizas_curated" LIMIT 30', engine)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,3,2025-02-14,540,42,4,9,1611.53,92.05,173298.36
1,4,2026-01-09,2821,40,10,5,1866.62,456.99,244461.27
2,7,2025-09-02,1254,25,11,4,1400.82,188.40,258202.93
3,10,2026-01-24,2281,69,13,3,791.38,67.44,20710.00
4,13,2025-08-19,1527,9,14,9,708.37,105.04,27042.54
5,14,2026-01-20,367,65,1,11,0.00,122.12,249504.31
6,19,2025-05-19,1693,50,3,9,1257.43,237.20,106454.95
7,23,2025-03-21,61,19,3,5,1403.46,112.05,163649.61
8,26,2025-07-29,2295,71,11,4,614.46,149.78,36670.97
9,27,2025-06-25,352,30,3,6,-1290.55,179.37,162227.75
10,28,2025-02-21,1213,65,8,9,464.73,25.26,18041.73
11,30,2025-05-07,2493,14,12,4,816.71,199.22,106724.98
12,33,2025-09-18,1034,67,2,8,73.63,13.25,6844.04
13,36,2025-12-06,2313,53,12,6,779.35,64.18,95204.18
14,37,2025-11-13,2846,75,10,3,800.22,104.70,66127.82
15,41,2025-10-11,3651,48,13,5,816.63,106.27,136809.90
16,43,2025-11-06,2657,8,6,1,-1261.22,106.86,248818.74
17,45,2025-12-11,2278,66,3,11,1539.37,240.41,114732.26
18,46,2025-04-11,2761,28,2,1,564.21,57.82,23965.61
19,49,2025-08-11,1122,2,14,4,337.32,69.59,47210.14
20,50,2025-02-22,717,49,15,10,518.78,86.45,66871.99
21,51,2025-06-04,2801,67,5,4,1612.80,321.59,156855.81
22,52,2025-01-24,1746,33,1,10,1429.69,78.50,173202.87
23,53,2025-09-29,1962,79,1,3,0.00,305.78,265915.68
24,54,2025-07-22,2969,3,4,3,421.01,63.89,13911.37
25,55,2026-12-02,2340,26,10,6,1954.65,431.08,150219.71
26,61,2025-03-07,1759,23,4,12,142.93,13.14,3134.79
27,62,2025-12-16,584,36,4,8,695.24,63.23,28262.23
28,63,2025-03-05,3691,55,10,7,-1680.49,242.41,238110.36
29,66,2025-03-04,1352,21,12,6,776.33,147.21,112829.12