<a href="https://colab.research.google.com/github/CatalinaDeras24/etl-data-pipeline/blob/main/Notebook/polizas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

In [11]:
url="https://raw.githubusercontent.com/CatalinaDeras24/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

In [12]:
df = pd.read_csv(url)

In [13]:
df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

Exploración de datos

In [14]:
df.shape

(25150, 9)

In [15]:
df.columns

Index(['id_poliza', 'fecha_emision', 'id_cliente', 'id_corredor',
       'id_aseguradora', 'id_tipo_seguro', 'prima', 'comision',
       'monto_asegurado'],
      dtype='object')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

In [17]:
df.isnull().sum()

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

Limpieza de datos

In [24]:
polizas= df.copy()

In [19]:
for col in polizas.select_dtypes(include='object').columns:
    polizas[col] = polizas[col].str.strip()

In [27]:
cols = ['prima', 'comision', 'monto_asegurado']

for col in cols:
    polizas[col] = polizas[col].astype(str).str.strip()
    polizas[col] = polizas[col].str.replace('.', '', regex=False).str.replace(',', '.', regex=False)
    polizas[col] = pd.to_numeric(polizas[col], errors='coerce')

In [28]:
polizas.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,82953.0,NaN,139253110.0
1,2,2026/02/16,2408,35,11,12,NaN,1222.0,2754432.0
2,3,02-14-25,540,42,4,9,1611530.0,9205.0,17329836.0
3,4,09-01-2026,2821,40,10,5,1866620.0,456990.0,244461270.0
4,5,2026-02-13,945,23,9,11,NaN,32408.0,123407750.0

Separar datos válidos y rechazados

Exportar archivos

Conectar con PostgreSQL Cloud

In [ ]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_a5iy_user:wejO7kM3iEylWf1mrkye7dj6P9rI4f6B@dpg-d6qu8ka4d50c73bk4lqg-a.oregon-postgres.render.com/etl_seguros_a5iy"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

Cargar datos en PostgreSQL

50

30

Validar la carga