<a href="https://colab.research.google.com/github/CatalinaDeras24/etl-data-pipeline/blob/main/Notebook/tipos_segur.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url="https://raw.githubusercontent.com/CatalinaDeras24/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"

In [4]:
df = pd.read_csv(url)

In [6]:
df.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

Exploracion de los datos

In [7]:
df.shape

(12, 4)

In [8]:
df.columns

Index(['id_tipo_seguro', 'tipo', 'categoria', 'riesgo_base'], dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

In [10]:
df.isnull().sum()

id_tipo_seguro    0
tipo              0
categoria         2
riesgo_base       2
dtype: int64

Limpieza de datos

In [11]:
tipos_seguro = df.copy()

In [12]:
for col in tipos_seguro.select_dtypes(include='object').columns:
    tipos_seguro[col] = tipos_seguro[col].str.strip()

In [14]:
tipos_seguro['categoria']= tipos_seguro['categoria'].replace(['', 'nan', 'None', 'NULL'], pd.NA)

In [15]:
tipos_seguro['riesgo_base']= tipos_seguro['riesgo_base'].replace(['-','', 'nan', 'None', 'NULL'], pd.NA)

In [18]:
tipos_seguro['categoria']= tipos_seguro['categoria'].str.capitalize()

In [21]:
tipos_seguro= tipos_seguro.drop_duplicates()

Separar datos válidos y rechazados

In [23]:
validos = tipos_seguro.dropna(
    subset=['categoria','riesgo_base']
).copy()

rechazados = tipos_seguro[
     tipos_seguro[['categoria', 'riesgo_base']]
    .isna()
    .any(axis=1)
].copy()

In [24]:
def motivo(row):
    motivos = []

    if pd.isna(row['categoria']):
        motivos.append("La categoria se encuentra vacio")

    if pd.isna(row['riesgo_base']):
        motivos.append("No cuenta con un riesgo base")

    return ", ".join(motivos)

In [25]:
rechazados['motivo'] = rechazados.apply(motivo, axis=1)

Exportar archivos

In [26]:
validos.to_csv("tipos_seguro_curated.csv", index=False)

rechazados.to_csv("tipos_seguro_rejects.csv", index=False)

Conectar con PostgreSQL Cloud

In [27]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_a5iy_user:wejO7kM3iEylWf1mrkye7dj6P9rI4f6B@dpg-d6qu8ka4d50c73bk4lqg-a.oregon-postgres.render.com/etl_seguros_a5iy"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 28.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

Cargar datos en PostgreSQL

In [28]:
validos.to_sql(
    'tipos_seguro_curated',
    engine,
    if_exists='append',
)

8

In [29]:
rechazados.to_sql(
    'tipos_seguro_rejects',
    engine,
    if_exists='append',
    index=False
)

4

Validar la carga

In [30]:
pd.read_sql('SELECT * FROM "tipos_seguro_curated" LIMIT 20', engine)

   index  id_tipo_seguro        tipo    categoria riesgo_base
0      1               2  Industrial  Empresarial        4.68
1      2               3  Industrial     Familiar        5.10
2      4               5        Auto  Empresarial        9.07
3      5               6  Industrial  Empresarial        2.52
4      6               7       Salud     Personal        0.92
5      7               8   Educación  Empresarial        7.42
6      9              10      Dental     Especial        2.70
7     10              11        Auto  Empresarial        4.33